# Generated by Django 4.2.2 on 2023-06-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_active',
            new_name='email_confirmed',
        ),
    ]
