# Generated by Django 4.2.2 on 2023-07-14 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20), django.core.validators.StepValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(editable=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20), django.core.validators.StepValueValidator(1)]),
        ),
    ]
