# Generated by Django 4.2.2 on 2023-07-07 17:15

from django.db import migrations, models
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_image_field_image_url_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(unique=True, upload_to=recipes.models.Image.image_path),
        ),
        migrations.AlterField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='tags', to='recipes.recipe'),
        ),
    ]
