# Generated by Django 4.2.2 on 2023-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_image_order_alter_step_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, choices=[('g', 'grams'), ('kg', 'kilograms'), ('mg', 'milligrams'), ('oz', 'ounces'), ('lb', 'pounds'), ('cup', 'cups'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('ml', 'milliliters'), ('l', 'liters'), ('piece', 'pieces')], max_length=20, null=True),
        ),
    ]
