# Generated by Django 4.2.2 on 2023-07-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='additional_informations',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
