# Generated by Django 4.2.2 on 2023-07-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_alter_image_unique_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='unique_identifier',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('recipe', 'unique_identifier')},
        ),
    ]
